### PR TITLE
Time Module

### PR DESCRIPTION
**Pull request by krizhan1997**

### CODE REVIEW

**Comment by krizhan1997** [comment]
hey i was having trouble with the test cases. is that normal??

**Comment by swapagarwal** [comment]
Yes, the tests have to be configured the first time. Now, they are working.

**Comment by swapagarwal** [comment]
Thanks @krizhan1997! :+1:

**Comment by krizhan1997** [comment]
lol yeahh. its my first time using github so its confusing. im trying to get the hang of it but i appreacite everything. thanks

**Comment by swapagarwal** [comment]
Sure, np! :smile:

**Pull request merged**
