### PR TITLE
Gender-neutral responses #215

### PR DESCRIPTION
**Pull request by sync350**
Edited the file to remove "sir" from the response if the bot is unable to
respond to the query. This still leaves room for someone to add a replace
command to get the sender_name variable, and allow the bot to address the
user by name (such as within the other modules), but for right now this seems
to be the best way to stay gender neutral.
I was looking at using a replace function, but so far have had no such luck.

### CODE REVIEW

**Comment by aviral1701** [comment]
@swapagarwal @sync350 I would like to do the additional work of fetching the name variable and displaying it out!

**Comment by sync350** [comment]
@aviral1701 @swapagarwal  That sounds fine to me :)

**Comment by aviral1701** [comment]
Let's just for @swapagarwal to respond on this one,then we can start the new work!

**Comment by swapagarwal** [comment]
Thanks @sync350! 👍 
@aviral1701 You may go ahead. 🏃

**Pull request merged**
