### PR TITLE
Add explainxkcd link

### PR DESCRIPTION
**Pull request by CassiusYCai**
https://github.com/swapagarwal/JARVIS-on-Messenger/issues/130

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thanks @CassiusYCai! 👍

**Comment by swapagarwal** [comment]
I see this is your first pull request. 🎉 
Congratulations, and welcome to the amazing world of open-source!

**Comment by CassiusYCai** [comment]
Thanks so much for the help and welcome :)

**Pull request merged**
