### PR TITLE
add images to ping response

### PR DESCRIPTION
**Pull request by leegenes**
Here is my first go at adding images for the ping response. Using the following images for statuses 1, 2, and 3 respectively.

Wasn't sure about size, or how to test appearance within Messenger to see how 240x240 scales.

First PR, any and all feedback on code and PR itself is much appreciated.

### CODE REVIEW

**Comment by leegenes** [comment]
@swapagarwal 
Where do you want to host font awesome images? Those don't have direct URLs. I'll follow your format for images, but ultimately won't update PR until +1 on images. 
Note: not a designer, not promising anything (:
Can you be more specific about your 'Can be removed?' comment? Followed format from another feature file. Script is currently using all of those modules.

**Comment by swapagarwal** [comment]
@leegenes TextTemplate was being used here: https://github.com/swapagarwal/JARVIS-on-Messenger/pull/206/files#diff-cbf722fe8210732365e30b664dc7a890L27
Since you removed that, I don't see a need for importing TextTemplate now.
Regarding link of images, if you go to the fa2png.io link mentioned above, and click on generate button, you get this url http://fa2png.io/media/icons/font-awesome/4-6-3/check-circle/256/0/27ae60_none.png :)

**Comment by leegenes** [comment]
The TextTemplate is still being used in the exception handling. Seems this should continue to be done for consistency throughout the rest of JARVIS. See line 41.

**Comment by swapagarwal** [comment]
@leegenes Good catch!

**Comment by swapagarwal** [comment]
Thanks @leegenes! 👍 
`ping` module just got a lot more awesome!! 🎉 
Congratulations for your first open-source contribution, and welcome to the amazing world of open-source. 😄

**Pull request merged**
