### PR TITLE
Offline datasrc quotes

### PR DESCRIPTION
**Pull request by nikhilgeo**
#54 
I have added a offline data source for quotes in /data/quotes.json. 
Please review.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Nice!
Can you add the source of the quote like:
```Some people are worth melting for. - Olaf (Frozen)```

**Comment by nikhilgeo** [comment]
Yeah Sure I will update the source too.
Thanks..

**Comment by nikhilgeo** [comment]
@swapagarwal, I have added author of each quote...

**Comment by swapagarwal** [comment]
Thanks @nikhilgeo! :+1:

**Comment by swapagarwal** [comment]
This is a really nice curation! :tada:

**Pull request merged**
