### PR TITLE
Reformat modules and templates

### PR DESCRIPTION
**Pull request by abhisheksp**

### CODE REVIEW

**Comment by swapagarwal** [comment]
Hey @abhisheksp Did you do this manually, or did you use a tool? I'm asking this so that if you used a tool, we can integrate it to our build/testing process.

**Comment by abhisheksp** [comment]
I use PyCharm which makes these checks among others. There are linters available for python which can be made as a mandatory step on the local build as well as CI.

Also merge the PR?

**Comment by swapagarwal** [comment]
Merged in 1e3dcbd19feb0c0a31bac69b83167f2ab5ff7e4c.
Also enabled style-check on future PRs.
Thanks @abhisheksp! 👍

**Comment by abhisheksp** [comment]
@swapagarwal why did you have to create a commit yourself?

**Comment by swapagarwal** [comment]
@abhisheksp Many files had changes after this PR, so there were a lot of merge conflicts. 😅 
You are welcome to work on other issues. 😄

**Pull request closed without merging**
