### PR TITLE
Add coin gif and modify coin.py

### PR DESCRIPTION
**Pull request by isbee**
I create coin .gif file(front.gif, back.gif) and modify coin.py.

gif file is executed from internal directory(/images)

### CODE REVIEW

**Comment by isbee** [comment]
#152

**Comment by isbee** [comment]
@swapagarwal I need your feedback about this. 
You have raised the issue so i have worked on it but I can not figure out if you like it.

If you think this commit is useless, let me know which part should be modified.

1. code
2. gif file
3. wrong PR 
4. or whatever

**Comment by swapagarwal** [comment]
Hey @isbee, thank you for taking the time to contribute. The PR looks good. 😇 
I got caught up in work, so couldn't devote much time here.
From where did you get the animations?

**Comment by isbee** [comment]
@swapagarwal I am glad that you liked it :)  
I made this animation using maya.  
_Can the animations be modified to include heads/tails?_   -> is this mean to change the text 'front/back' in coin to 'Head/Tail' ?

**Comment by swapagarwal** [comment]
Yes, as Heads / Tails are more intuitive in case of coins. 😄

**Comment by isbee** [comment]
I made some mistakes to this PR so i close this and reopen #353

**Pull request closed without merging**
