### PR TITLE
Abstracting location entity as requested by issue #337

### PR DESCRIPTION
**Pull request by gibertoni**
Adding a location module to abstract the use of the Google Maps API (geocode)
Is this the desired approach to issue #337?

Also, my editor follows PEP08 guideline and I changed some formatting on the files I edited.
Please tell me if this is not desired or if the code is less readable this way.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thank you for taking the time to contribute! This is sincerely appreciated. 😇

**Comment by swapagarwal** [comment]
Hey @gibertoni, this task just required merging the entities, i.e. renaming `weather_location` and `time_location` to `location`. 😄

**Comment by gibertoni** [comment]
I see.
Since the entity is something we created on wit.ai, shouldn't it be edited there?
I don't understand how I handle it on the jarvis/module code.
Can you point me to a starting point?

**Comment by gibertoni** [comment]
I see. I think I understand it now.
So I should update the time.py and weather.py modules to expect an entity called 'location'
And then, you will update wit.ai to return the entity with the value 'location' for those cases. 
Is that right?

**Pull request closed without merging**
