### PR TITLE
2 weather

### PR DESCRIPTION
**Pull request by toanngosy**
I just delete one. How can I test Jarvis on my laptop? I run --- python Jarvis.py ---  on Terminal and then http://localhost:5000/process/?q=<"hello"> but nothing happens. Im new to this so thanks gratefully :D

### CODE REVIEW

**Comment by swapagarwal** [comment]
Query like this: `http://localhost:5000/process/?q=<"hello">`

**Comment by toanngosy** [comment]
[toanngo@toanngo-mint] ~/JARVIS-on-Messenger (master) 
❯ python jarvis.py      
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader
http://localhost:5000/process/?q=hello


------------------------------------------------------------------
This is on my terminal, but there is no response. Did I do it right?

**Comment by swapagarwal** [comment]
After running `python jarvis.py` in the terminal, visit `http://localhost:5000/process/?q=hello` in a web browser. You should get a json response.

**Comment by swapagarwal** [comment]
Nice catch! :smile:
There were some merge conflicts (I made a lot of changes here and there) so I fixed this in 656727f5df36409ed2bbd05db53828532de304cd.
Thanks @toanngosy! :+1:

**Pull request closed without merging**
