### PR TITLE
Update anime.py

### PR DESCRIPTION
**Pull request by krizhan1997**
Format rating into two decimal places. 4.3233223 = 4.32
However, if the rating is 4.00, it becomes 4 rather than staying at 4.00 since 0 is redundant. But I can add it if u want.

### CODE REVIEW

**Comment by swapagarwal** [comment]
A better option would be to use [`round`](https://docs.python.org/2/library/functions.html#round) :smile:

**Comment by krizhan1997** [comment]
lol thanks thoo. hey i was wondering if there was a module i can try building for jarvis? just to get some hands on experience. anything u advice? i plan on working on it thoroughly since I finally have more free time and make sure it works just so I can better myself and get more experience. thanks for all the help tho

**Comment by krizhan1997** [comment]
actually i will try working on the time module. if thats alright??

**Comment by swapagarwal** [comment]
Sure, the low-hanging fruits are just meant to get started with the project. Now, you can move on to tackle larger issues. You can go ahead with any new module you like. If it's a one that's not mentioned in the README, it'd be better if you open an issue regarding the same. Hit me up if you need any help. Cheers!

**Comment by swapagarwal** [comment]
Thanks @krizhan1997! :+1:

**Pull request merged**
