### PR TITLE
Weather module

### PR DESCRIPTION
**Pull request by antixcode6**
I think I finally dug myself out of the hole I created with that last pull request @swapagarwal

### CODE REVIEW

**Comment by swapagarwal** [comment]
Great! :tada: 
I promise this is the last change before merging, can you run the following commands?
`git reset 2c988b974133e35099e5ad8e9928ad97bfcc015c`
`git fetch upstream`
`git checkout master`
`git merge upstream/master`
Then add the two weather files and add the corresponding line in `__init__.py`
Your fork is out of [sync](https://help.github.com/articles/syncing-a-fork/), that's why there are merge conflicts!

**Comment by swapagarwal** [comment]
Hey @antixcode6 , will you be willing to complete this? :smile:

**Comment by williamshoops96** [comment]
@swapagarwal Hey there, seen as you've yet to get a reply from the original pr submitter I've decided to take on his code. Just adapting it now!:)

**Comment by swapagarwal** [comment]
Continued in #76

**Comment by williamshoops96** [comment]
Changed to #79

**Pull request closed without merging**
