### PR TITLE
Added error message for currency conversions

### PR DESCRIPTION
**Pull request by camdroid**

### CODE REVIEW

**Comment by swapagarwal** [comment]
Hey @camdroid, it'd be better if you set the error message before the status.

**Comment by camdroid** [comment]
Okay, that's fine. Out of curiosity, why?

**Comment by swapagarwal** [comment]
Well, it should be consistent with the previous code (see dictionary module). Also, the status flag should ideally be set at the end! Hope that makes sense.

**Comment by swapagarwal** [comment]
Thanks @camdroid! :+1:

**Pull request merged**
