### PR TITLE
Check Time Anywhere

### PR DESCRIPTION
**Pull request by krizhan1997**
eg.time in beijing or time in los angeles.
My first module. I feel like I may have messed up since its my first time and any feedback (even negative) regarding my code or even anything is much appreciated since its a learning experience.

### CODE REVIEW

**Comment by krizhan1997** [comment]
Just want to make sure this is alright.

**Comment by swapagarwal** [comment]
Hey @krizhan1997, nice work! :smile: 
Seeing the [usage policy](http://wiki.openstreetmap.org/wiki/Nominatim#Usage_Policy), I think it's better to use MapQuest API.

**Comment by krizhan1997** [comment]
ohh. ok np

**Comment by swapagarwal** [comment]
Continued in #62

**Pull request closed without merging**
