### PR TITLE
Tests for test_fact.py

### PR DESCRIPTION
**Pull request by edadesd**
I added some unit tests to test_facts.py that examine the contents of the response. These tests should ensure that the response includes a line from the facts file, as well as the intended number and types of quick replies.

### CODE REVIEW

**Comment by edadesd** [comment]
The subsequent commits made the style corrections requested by @stickler-ci .

**Comment by swapagarwal** [comment]
Hi @edadesd, I recently integrated @stickler-ci into PRs, to have a proper style-guide for the code. How was your experience with it?
The tests look good. 😄 
There is some conflict in the file; Can you rebase your work on top of current master?

**Comment by edadesd** [comment]
@stickler-ci seemed really adamant over invisible things, but it was nice to see the automated style checking. I was able to search for the style manual codes it stated in order to figure out exactly what it thought the problem was and what it expected me to do instead.

**Comment by edadesd** [comment]
It looks like I've cleared the conflict.

**Comment by edadesd** [comment]
Squashed the commits to clean up the history.

**Comment by edadesd** [comment]
Going to re-open this as a branch with my other unit test PR merged.

**Pull request closed without merging**
