### PR TITLE
Added Windows Development Insturctions

### PR DESCRIPTION
**Pull request by austinprog**
I added the Windows Instructions for getting the development machine up in running if you happen to use it. I saw on the Glitter chat that someone was using Windows and needed some help on downloading and getting everything up and running.

### CODE REVIEW

**Comment by swapagarwal** [comment]
@austinprog So basically, only step 2 is not required?

**Comment by austinprog** [comment]
Oh ops forgot to add the other step

**Comment by swapagarwal** [comment]
@austinprog No need to close this, you can add more commits to this PR itself. :smile:

**Comment by swapagarwal** [comment]
@austinprog Instead of copying it to other section, we can split step 2 into 2a, 2b kind of thing as rest of the steps are exactly the same.

**Comment by austinprog** [comment]
@swapagarwal  Sorry for the delay on the instructions. I have been busy with my summer classes. I will finish my instructions and send in a new pull request as soon as I can.

**Comment by swapagarwal** [comment]
Thanks @austinprog! 👍

**Pull request merged**
