### PR TITLE
Time format

### PR DESCRIPTION
**Pull request by nikhilgeo**
PR for issue #80 

time format changed to 
"%a %b %d %Y %H:%M:%S" than corresponds to "Thu Jun 09 2016 13:24:43"

### CODE REVIEW

**Comment by swapagarwal** [comment]
There should only be one file changed here: https://github.com/swapagarwal/JARVIS-on-Messenger/pull/84/files

**Comment by nikhilgeo** [comment]
I'm not sure what should be done to remove those commits...
Any advice..?

**Comment by swapagarwal** [comment]
Well, you should always check out a new branch from master after syncing the fork: https://help.github.com/articles/syncing-a-fork/

**Comment by nikhilgeo** [comment]
thanks for the pointing it out..
So should I create a new PR..?

**Comment by swapagarwal** [comment]
Well, the easiest indeed is to create a new PR.
However, if you'd like to dive in (and have the time to do so), you can learn about `rebasing`.

**Comment by nikhilgeo** [comment]
@swapagarwal I tried rebasing.....didn't go well it seems....I will create a new PR..

**Comment by swapagarwal** [comment]
Continued in #85

**Pull request closed without merging**
