### PR TITLE
Added Dice roll functionality

### PR DESCRIPTION
**Pull request by UshalNaidoo**
Added a dice roll feature.
The files are src/dice.py and tests/test_dice.py

### CODE REVIEW

**Comment by JPHamlett1993** [comment]
Looks good to me! Nice work!

**Comment by UshalNaidoo** [comment]
Thanks, not too sure why the tests are failing

**Comment by JPHamlett1993** [comment]
It is because @swapagarwal hasn't trained wit.ai for your tests.

**Comment by swapagarwal** [comment]
Thanks @UshalNaidoo! 👍

**Pull request merged**
