### PR TITLE
Add additional requirements for testing in arch linux.

### PR DESCRIPTION
**Pull request by LukaK**
Hello,
I have followed instructions in `README/Local developement/Testing` page for starting and got two failures when running test. Test in questions are `test_pydist` and `test_keygen`.

I'm using Arch linux 4.8.13-1 and as a substitute for `libssl-dev` I've installed `openssl` since there is no `libssl-dev`.

This pull request fixes things.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Can any other arch user verify this?

**Comment by swapagarwal** [comment]
@Icyphox Cool, could you also verify the packages added [here](https://github.com/swapagarwal/JARVIS-on-Messenger/pull/138/files)?

**Comment by Icyphox** [comment]
Okay I know what `keyring` and `keyring.alt` are for, but I really can't tell why you'll need them here. And `jsonschema` too seems redundant. @LukaK, could you explain?

**Comment by LukaK** [comment]
Sorry for the late reply guys. I've tested repository on a fresh install of arch linux and tests pass. Tests also pass on my home system after fixing some python version problems (tnx for that :D).

So only thing is to install `libffi` and `openssl` instead of `libffi-dev` and `libssl-dev`. Would you like this to be included in the readme?

**Comment by swapagarwal** [comment]
@LukaK No problem!
Cool. You can update this PR with an additional section for Arch Linux under point number 2 here: https://github.com/swapagarwal/JARVIS-on-Messenger/blob/master/README.md#local-development--testing
Also, reset the requirements.txt file to original one. So you should see only changes in README.md here: https://github.com/swapagarwal/JARVIS-on-Messenger/pull/138/files

**Comment by LukaK** [comment]
@swapagarwal Finished!

I've also added Fedora section to cover major distributions and package managers. Hope it is ok.

**Comment by swapagarwal** [comment]
Thanks @LukaK! 👍

**Pull request merged**
