### PR TITLE
Move from hello.py to bye.py

### PR DESCRIPTION
**Pull request by dkansk1323**
Move 'Sir, I think I need to sleep now...' from hello to bye

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thank you for taking the time to contribute! This is sincerely appreciated. 😇

**Comment by dkansk1323** [comment]
It's really good experience to me. thank you for interest

**Comment by nmshaikh** [comment]
Am I correct in understanding that this change should fix the issue where JARVIS says 'Sir, I think I need to sleep now...' when the user says 'hi jarvis' or something similar? Because I still get that reply when I say hi sometimes

**Comment by Androbin** [comment]
What exactly is blocking this PR?

**Comment by Csear007** [comment]
@Androbin I don't think anything is blocking it but rather nobody thought to close it after the merge

**Comment by Androbin** [comment]
@Csear007 Merge what of? These changes aren't on `master`...

**Comment by Csear007** [comment]
Oh sorry I thought it was merged already, nevermind my previous comment.

**Comment by swapagarwal** [comment]
@Androbin Not getting much time to devote on this lately.

**Comment by swapagarwal** [comment]
Thanks @dkansk1323! 👍

**Pull request merged**
