### PR TITLE
League Table feature

### PR DESCRIPTION
**Pull request by dgrah50**
This is my first time using GitHub or contributing to a community project!
I have written a module that can display the football league tables of the top 5 European leagues; England , Spain, Germany, Italy or France.  The module uses BeautifulSoup to scrape the data from Guardian Football.
I would like the wit.ai to feed in the name of the country using **entities** so that the module knows which league to retrieve from Guardian.
The module will currently fail checks as it has a dependency on the BeautifulSoup Library.
I would be thankful for any feedback.

### CODE REVIEW

**Comment by rennhak** [comment]
> This is my first time using GitHub or contributing to a community project!

Thank you for contributing!

**Comment by conormag94** [comment]
@swapagarwal @dgrah50 If you are still looking for an API for this, I have used this API for a project in the past and found it very good. http://www.football-data.org/index

It has a league table API call as well which could easily be used.

**Comment by swapagarwal** [comment]
@dgrah50 Would you be willing to complete this?

**Comment by dgrah50** [comment]
Yes I can do this

**Comment by horrormyth** [comment]
@dgrah50 Looks like this has gone stale :)

**Comment by addyvm22** [comment]
Hello i have written the code with an api call for this feature...Please check it out over here... https://github.com/dgrah50/JARVIS-on-Messenger/pull/1
@dgrah50 @swapagarwal

**Pull request closed without merging**
