### PR TITLE
Added a few quotes

### PR DESCRIPTION
**Pull request by sarthak5**
Added a few more quotes to quotes.json, as my first contribution.

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thanks @sarthak5! 👍
There were some merge conflicts, so had to resolve them manually.
Merged in 5e6fcf75b525347918222205d3abe65b2bd97b9e

**Comment by swapagarwal** [comment]
I was thinking of separating this into two modules: `quote` and `motivation`, essentially, filter out motivational ones. Would you like to pick it up?

**Comment by sarthak5** [comment]
Yes definitely I would like to contribute.

**Comment by sarthak5** [comment]
Would you like to keep motivational quotes in both modules quote and motivation or remove them entirely from quote?

**Comment by sarthak5** [comment]
I have added motivation.json (#134), but I have not changed quotes.json. Do you want to remove motivational quotes from quotes.json?

**Comment by swapagarwal** [comment]
I'd prefer removing them.

**Pull request closed without merging**
