### PR TITLE
Issue and PR template

### PR DESCRIPTION
**Pull request by manparvesh**
#### Short description of what this resolves:
Adds Issue and PR template. This project really needs it

**Fixes**: #293

### CODE REVIEW

**Comment by swapagarwal** [comment]
Thank you for taking the time to contribute! This is sincerely appreciated. 😇

(Powered by [GitMate.io](https://gitmate.io))

**Comment by swapagarwal** [comment]
Thanks @manparvesh for adding the much-needed templates.
Not sure why codecov is here? 🤔

**Comment by manparvesh** [comment]
Just ignore that, earlier I added this commit after adding codecov in my master branch. Then I moved that to a different branch.

**Comment by swapagarwal** [comment]
Thanks @manparvesh! 👍

**Pull request merged**
